name: Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  trigger-nightly-publish:
    uses: ./.github/workflows/publish.yml
    with:
      git_ref: ${{ github.ref }}
      mode: Nightly
