name: Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  Nightly:
    uses: ./.github/workflows/publish.yml
    with:
      git_ref: master
      mode: Nightly
    secrets: inherit
