name: Release Suite

on:
  push:
    tags:
      - v0.*
      - v1.*

jobs:
  trigger-release-publish:
    uses: ./.github/workflows/publish.yml
    with:
      git_ref: ${{ github.ref }}
      mode: release
